# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import administracion_pb2 as administracion__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in administracion_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServidorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegistroVendedor = channel.unary_unary(
                '/vendedores.Servidor/RegistroVendedor',
                request_serializer=administracion__pb2.Vendedor.SerializeToString,
                response_deserializer=administracion__pb2.Status.FromString,
                _registered_method=True)
        self.RegistroTienda = channel.unary_unary(
                '/vendedores.Servidor/RegistroTienda',
                request_serializer=administracion__pb2.Tienda.SerializeToString,
                response_deserializer=administracion__pb2.Status.FromString,
                _registered_method=True)
        self.RegistroAsignacion = channel.unary_unary(
                '/vendedores.Servidor/RegistroAsignacion',
                request_serializer=administracion__pb2.Asignacion.SerializeToString,
                response_deserializer=administracion__pb2.Status.FromString,
                _registered_method=True)
        self.listadoTienda = channel.unary_stream(
                '/vendedores.Servidor/listadoTienda',
                request_serializer=administracion__pb2.Empty.SerializeToString,
                response_deserializer=administracion__pb2.Tienda.FromString,
                _registered_method=True)
        self.listadoVendedor = channel.unary_stream(
                '/vendedores.Servidor/listadoVendedor',
                request_serializer=administracion__pb2.Empty.SerializeToString,
                response_deserializer=administracion__pb2.Vendedor.FromString,
                _registered_method=True)
        self.listadoAsignaciones = channel.unary_stream(
                '/vendedores.Servidor/listadoAsignaciones',
                request_serializer=administracion__pb2.Empty.SerializeToString,
                response_deserializer=administracion__pb2.ListadoAsignaciones.FromString,
                _registered_method=True)
        self.agregaProducto = channel.stream_unary(
                '/vendedores.Servidor/agregaProducto',
                request_serializer=administracion__pb2.Producto.SerializeToString,
                response_deserializer=administracion__pb2.Status.FromString,
                _registered_method=True)
        self.ListadoProductos = channel.unary_stream(
                '/vendedores.Servidor/ListadoProductos',
                request_serializer=administracion__pb2.Empty.SerializeToString,
                response_deserializer=administracion__pb2.Producto.FromString,
                _registered_method=True)


class ServidorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegistroVendedor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegistroTienda(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegistroAsignacion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listadoTienda(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listadoVendedor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listadoAsignaciones(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def agregaProducto(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListadoProductos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServidorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegistroVendedor': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistroVendedor,
                    request_deserializer=administracion__pb2.Vendedor.FromString,
                    response_serializer=administracion__pb2.Status.SerializeToString,
            ),
            'RegistroTienda': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistroTienda,
                    request_deserializer=administracion__pb2.Tienda.FromString,
                    response_serializer=administracion__pb2.Status.SerializeToString,
            ),
            'RegistroAsignacion': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistroAsignacion,
                    request_deserializer=administracion__pb2.Asignacion.FromString,
                    response_serializer=administracion__pb2.Status.SerializeToString,
            ),
            'listadoTienda': grpc.unary_stream_rpc_method_handler(
                    servicer.listadoTienda,
                    request_deserializer=administracion__pb2.Empty.FromString,
                    response_serializer=administracion__pb2.Tienda.SerializeToString,
            ),
            'listadoVendedor': grpc.unary_stream_rpc_method_handler(
                    servicer.listadoVendedor,
                    request_deserializer=administracion__pb2.Empty.FromString,
                    response_serializer=administracion__pb2.Vendedor.SerializeToString,
            ),
            'listadoAsignaciones': grpc.unary_stream_rpc_method_handler(
                    servicer.listadoAsignaciones,
                    request_deserializer=administracion__pb2.Empty.FromString,
                    response_serializer=administracion__pb2.ListadoAsignaciones.SerializeToString,
            ),
            'agregaProducto': grpc.stream_unary_rpc_method_handler(
                    servicer.agregaProducto,
                    request_deserializer=administracion__pb2.Producto.FromString,
                    response_serializer=administracion__pb2.Status.SerializeToString,
            ),
            'ListadoProductos': grpc.unary_stream_rpc_method_handler(
                    servicer.ListadoProductos,
                    request_deserializer=administracion__pb2.Empty.FromString,
                    response_serializer=administracion__pb2.Producto.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vendedores.Servidor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vendedores.Servidor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Servidor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegistroVendedor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vendedores.Servidor/RegistroVendedor',
            administracion__pb2.Vendedor.SerializeToString,
            administracion__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegistroTienda(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vendedores.Servidor/RegistroTienda',
            administracion__pb2.Tienda.SerializeToString,
            administracion__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegistroAsignacion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vendedores.Servidor/RegistroAsignacion',
            administracion__pb2.Asignacion.SerializeToString,
            administracion__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listadoTienda(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vendedores.Servidor/listadoTienda',
            administracion__pb2.Empty.SerializeToString,
            administracion__pb2.Tienda.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listadoVendedor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vendedores.Servidor/listadoVendedor',
            administracion__pb2.Empty.SerializeToString,
            administracion__pb2.Vendedor.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listadoAsignaciones(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vendedores.Servidor/listadoAsignaciones',
            administracion__pb2.Empty.SerializeToString,
            administracion__pb2.ListadoAsignaciones.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def agregaProducto(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/vendedores.Servidor/agregaProducto',
            administracion__pb2.Producto.SerializeToString,
            administracion__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListadoProductos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vendedores.Servidor/ListadoProductos',
            administracion__pb2.Empty.SerializeToString,
            administracion__pb2.Producto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
