# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: administracion.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'administracion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61\x64ministracion.proto\x12\nvendedores\"\x07\n\x05\x45mpty\"(\n\x06Status\x12\x13\n\x06status\x18\x01 \x01(\x08H\x00\x88\x01\x01\x42\t\n\x07_status\"E\n\x08Vendedor\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x0c\n\x04\x65\x64\x61\x64\x18\x03 \x01(\x05\x12\x0f\n\x07salario\x18\x04 \x01(\x05\";\n\x06Tienda\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65scripcion\x18\x02 \x01(\t\x12\x10\n\x08\x61lcaldia\x18\x03 \x01(\t\"H\n\nAsignacion\x12\x14\n\x0cidasignacion\x18\x01 \x01(\x05\x12\x10\n\x08idtienda\x18\x02 \x01(\x05\x12\x12\n\nidvendedor\x18\x03 \x01(\x05\"=\n\x08Producto\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08\x63\x61ntidad\x18\x02 \x01(\x05\x12\x13\n\x0b\x64\x65scripcion\x18\x03 \x01(\t\"C\n\x13ListadoAsignaciones\x12,\n\x0c\x61signaciones\x18\x01 \x03(\x0b\x32\x16.vendedores.Asignacion2\x96\x04\n\x08Servidor\x12>\n\x10RegistroVendedor\x12\x14.vendedores.Vendedor\x1a\x12.vendedores.Status\"\x00\x12:\n\x0eRegistroTienda\x12\x12.vendedores.Tienda\x1a\x12.vendedores.Status\"\x00\x12\x42\n\x12RegistroAsignacion\x12\x16.vendedores.Asignacion\x1a\x12.vendedores.Status\"\x00\x12:\n\rlistadoTienda\x12\x11.vendedores.Empty\x1a\x12.vendedores.Tienda\"\x00\x30\x01\x12>\n\x0flistadoVendedor\x12\x11.vendedores.Empty\x1a\x14.vendedores.Vendedor\"\x00\x30\x01\x12M\n\x13listadoAsignaciones\x12\x11.vendedores.Empty\x1a\x1f.vendedores.ListadoAsignaciones\"\x00\x30\x01\x12>\n\x0e\x61gregaProducto\x12\x14.vendedores.Producto\x1a\x12.vendedores.Status\"\x00(\x01\x12?\n\x10ListadoProductos\x12\x11.vendedores.Empty\x1a\x14.vendedores.Producto\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'administracion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=36
  _globals['_EMPTY']._serialized_end=43
  _globals['_STATUS']._serialized_start=45
  _globals['_STATUS']._serialized_end=85
  _globals['_VENDEDOR']._serialized_start=87
  _globals['_VENDEDOR']._serialized_end=156
  _globals['_TIENDA']._serialized_start=158
  _globals['_TIENDA']._serialized_end=217
  _globals['_ASIGNACION']._serialized_start=219
  _globals['_ASIGNACION']._serialized_end=291
  _globals['_PRODUCTO']._serialized_start=293
  _globals['_PRODUCTO']._serialized_end=354
  _globals['_LISTADOASIGNACIONES']._serialized_start=356
  _globals['_LISTADOASIGNACIONES']._serialized_end=423
  _globals['_SERVIDOR']._serialized_start=426
  _globals['_SERVIDOR']._serialized_end=960
# @@protoc_insertion_point(module_scope)
