# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: holamundo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'holamundo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fholamundo.proto\x12\tholamundo\"\x1d\n\x0bHolaRequest\x12\x0e\n\x06nombre\x18\x01 \x01(\t\"\x1f\n\x0cHolaResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2F\n\tSaludador\x12\x39\n\x06\x64iHola\x12\x16.holamundo.HolaRequest\x1a\x17.holamundo.HolaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'holamundo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HOLAREQUEST']._serialized_start=30
  _globals['_HOLAREQUEST']._serialized_end=59
  _globals['_HOLARESPONSE']._serialized_start=61
  _globals['_HOLARESPONSE']._serialized_end=92
  _globals['_SALUDADOR']._serialized_start=94
  _globals['_SALUDADOR']._serialized_end=164
# @@protoc_insertion_point(module_scope)
