# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autenticador.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autenticador.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61utenticador.proto\x12\x0c\x61utenticador\"j\n\x15\x41uthenticationRequest\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x17\n\x0fLugarNacimiento\x18\x02 \x01(\t\x12\x16\n\x0e\x41nioNacimiento\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"6\n\x13\x41uthenticationReply\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x08\x32\x64\n\x0c\x41utenticador\x12T\n\nautenticar\x12#.autenticador.AuthenticationRequest\x1a!.autenticador.AuthenticationReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autenticador_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHENTICATIONREQUEST']._serialized_start=36
  _globals['_AUTHENTICATIONREQUEST']._serialized_end=142
  _globals['_AUTHENTICATIONREPLY']._serialized_start=144
  _globals['_AUTHENTICATIONREPLY']._serialized_end=198
  _globals['_AUTENTICADOR']._serialized_start=200
  _globals['_AUTENTICADOR']._serialized_end=300
# @@protoc_insertion_point(module_scope)
