# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: comunicacion.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'comunicacion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63omunicacion.proto\x12\x0e\x63omunicaciones\"\x07\n\x05\x45mpty\"L\n\x08\x45lemento\x12\x0f\n\x02id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x18\n\x0b\x64\x65scripcion\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x05\n\x03_idB\x0e\n\x0c_descripcion\"(\n\x06Status\x12\x13\n\x06status\x18\x01 \x01(\x08H\x00\x88\x01\x01\x42\t\n\x07_status\"=\n\x10ListadoElementos\x12)\n\x07objetos\x18\x01 \x03(\x0b\x32\x18.comunicaciones.Elemento2\xda\x01\n\x0b\x43omunicador\x12@\n\tlistador1\x12\x15.comunicaciones.Empty\x1a\x18.comunicaciones.Elemento\"\x00\x30\x01\x12\x46\n\tlistador2\x12\x15.comunicaciones.Empty\x1a .comunicaciones.ListadoElementos\"\x00\x12\x41\n\tagregador\x12\x18.comunicaciones.Elemento\x1a\x16.comunicaciones.Status\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comunicacion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=38
  _globals['_EMPTY']._serialized_end=45
  _globals['_ELEMENTO']._serialized_start=47
  _globals['_ELEMENTO']._serialized_end=123
  _globals['_STATUS']._serialized_start=125
  _globals['_STATUS']._serialized_end=165
  _globals['_LISTADOELEMENTOS']._serialized_start=167
  _globals['_LISTADOELEMENTOS']._serialized_end=228
  _globals['_COMUNICADOR']._serialized_start=231
  _globals['_COMUNICADOR']._serialized_end=449
# @@protoc_insertion_point(module_scope)
