# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import comunicacion_pb2 as comunicacion__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in comunicacion_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ComunicadorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.listador1 = channel.unary_stream(
                '/comunicaciones.Comunicador/listador1',
                request_serializer=comunicacion__pb2.Empty.SerializeToString,
                response_deserializer=comunicacion__pb2.Elemento.FromString,
                _registered_method=True)
        self.listador2 = channel.unary_unary(
                '/comunicaciones.Comunicador/listador2',
                request_serializer=comunicacion__pb2.Empty.SerializeToString,
                response_deserializer=comunicacion__pb2.ListadoElementos.FromString,
                _registered_method=True)
        self.agregador = channel.stream_unary(
                '/comunicaciones.Comunicador/agregador',
                request_serializer=comunicacion__pb2.Elemento.SerializeToString,
                response_deserializer=comunicacion__pb2.Status.FromString,
                _registered_method=True)


class ComunicadorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def listador1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listador2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def agregador(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComunicadorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'listador1': grpc.unary_stream_rpc_method_handler(
                    servicer.listador1,
                    request_deserializer=comunicacion__pb2.Empty.FromString,
                    response_serializer=comunicacion__pb2.Elemento.SerializeToString,
            ),
            'listador2': grpc.unary_unary_rpc_method_handler(
                    servicer.listador2,
                    request_deserializer=comunicacion__pb2.Empty.FromString,
                    response_serializer=comunicacion__pb2.ListadoElementos.SerializeToString,
            ),
            'agregador': grpc.stream_unary_rpc_method_handler(
                    servicer.agregador,
                    request_deserializer=comunicacion__pb2.Elemento.FromString,
                    response_serializer=comunicacion__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'comunicaciones.Comunicador', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('comunicaciones.Comunicador', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Comunicador(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def listador1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/comunicaciones.Comunicador/listador1',
            comunicacion__pb2.Empty.SerializeToString,
            comunicacion__pb2.Elemento.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listador2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/comunicaciones.Comunicador/listador2',
            comunicacion__pb2.Empty.SerializeToString,
            comunicacion__pb2.ListadoElementos.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def agregador(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/comunicaciones.Comunicador/agregador',
            comunicacion__pb2.Elemento.SerializeToString,
            comunicacion__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
